name: New Scheduling

on:
 schedule: 
   - cron: "*/1 * * * *"
jobs: 
    Simple_schedule:
      runs-on: windows-latest
           
      steps:
        - name: echo a string
          run: echo "Hello"
        - name: multiline script
          run: |
            ls
            node -v
            npm -v
      